// message key
export const message = {
    successfully_updated: 'successfully.updated',
    successfully_created: 'successfully.created',
    please_give_a_name: 'please.give.a.name',
    must_be_greater_than_x0_letters: 'must.be.greater.than.x0.letters',
    equal_or_greater_x0_letters: 'equal.or.greater.x0.letters',
    equal_or_less_x0_letters: 'equal.or.less.x0.letters',
    successfully_deleted: 'successfully.deleted',
    confirm: 'confirm',
    do_you_want_to_delete: 'do.you.want.to.delete',
    delete: 'delete',
    cancel: 'cancel',
    yes: 'yes',
    no: 'no',
    this_field_is_required: 'this.field.is.required',
    must_be_numeric: 'must.be.numeric',
    select_date: 'select.date',
    amount_is_required: 'amount.is.required',
    amount_must_be_numeric: 'amount.must.be.numeric',
    amount_must_be_positive: 'amount.must.be.positive',
    amount_exceeds: 'amount.exceeds',
}