using Core.Interfaces.Data;
using Module.Core.Entities;
using System.Collections.Generic;

namespace Module.Core.Data
{
    public class CurrencySeed : ISeed<Currency>
    {
        public IEnumerable<Currency> GetSeeds()
        {
            return new List<Currency>
            {
                new Currency { Id = 1, Name = "UAE dirham", Code3 = "AED", Symbol = "AED", Plural = "UAE dirhams" },
                new Currency { Id = 2, Name = "Afghani", Code3 = "AFN", Symbol = "؋", Plural = "Afganis" },
                new Currency { Id = 3, Name = "Lek", Code3 = "ALL", Symbol = "Lek", Plural = "Lekë" },
                new Currency { Id = 4, Name = "Armenian dram", Code3 = "AMD", Symbol = "֏", Plural = "Armenian drams" },
                new Currency { Id = 5, Name = "Netherlands Antillean guilder", Code3 = "ANG", Symbol = "ƒ", Plural = "Netherlands Antillean guilders" },
                new Currency { Id = 6, Name = "Kwanza", Code3 = "AOA", Symbol = "Kz", Plural = "Kwanzas" },
                new Currency { Id = 7, Name = "Argentinian peso", Code3 = "ARS", Symbol = "$", Plural = "Argentinian pesos" },
                new Currency { Id = 8, Name = "Australian dollar", Code3 = "AUD", Symbol = "$", Plural = "Australian dollars" },
                new Currency { Id = 9, Name = "Aruban florin", Code3 = "AWG", Symbol = "ƒ", Plural = "Aruban florin" },
                new Currency { Id = 10, Name = "New Manat", Code3 = "AZN", Symbol = "ман", Plural = "New Manat" },
                new Currency { Id = 11, Name = "Convertible Marks", Code3 = "BAM", Symbol = "KM", Plural = "Convertible Marks" },
                new Currency { Id = 12, Name = "Barbados dollar", Code3 = "BBD", Symbol = "$", Plural = "Barbados dollars" },
                new Currency { Id = 13, Name = "Taka", Code3 = "BDT", Symbol = "৳", Plural = "Takas" },
                new Currency { Id = 14, Name = "Lev", Code3 = "BGN", Symbol = "лв", Plural = "Leva" },
                new Currency { Id = 15, Name = "Bahraini dinar", Code3 = "BHD", Symbol = "BD", Plural = "Bahraini dinars" },
                new Currency { Id = 16, Name = "Burundi franc", Code3 = "BIF", Symbol = "FBu", Plural = "Burundi francs" },
                new Currency { Id = 17, Name = "Bermuda dollar", Code3 = "BMD", Symbol = "$", Plural = "Bermuda dollars" },
                new Currency { Id = 18, Name = "Brunei dollar", Code3 = "BND", Symbol = "$", Plural = "Brunei dollars" },
                new Currency { Id = 19, Name = "Boliviano", Code3 = "BOB", Symbol = "$b", Plural = "Bolivianos" },
                new Currency { Id = 20, Name = "Real", Code3 = "BRL", Symbol = "R$", Plural = "Reales" },
                new Currency { Id = 21, Name = "Bahamian dollar", Code3 = "BSD", Symbol = "$", Plural = "Bahamian dollars" },
                new Currency { Id = 22, Name = "Ngultrum", Code3 = "BTN", Symbol = "Nu.", Plural = "Ngultrums" },
                new Currency { Id = 23, Name = "Pula", Code3 = "BWP", Symbol = "P", Plural = "Pula" },
                new Currency { Id = 24, Name = "Belarussian rouble", Code3 = "BYR", Symbol = "p.", Plural = "Belarussian roubles" },
                new Currency { Id = 25, Name = "Belize dollar", Code3 = "BZD", Symbol = "BZ$", Plural = "Belize dollars" },
                new Currency { Id = 26, Name = "Canadian dollar", Code3 = "CAD", Symbol = "$", Plural = "Canadian dollars" },
                new Currency { Id = 27, Name = "Franc congolais", Code3 = "CDF", Symbol = "₣", Plural = "Francs congolais" },
                new Currency { Id = 28, Name = "Swiss franc", Code3 = "CHF", Symbol = "CHF", Plural = "Swiss francs" },
                new Currency { Id = 29, Name = "Chilean peso", Code3 = "CLP", Symbol = "$", Plural = "Chilean pesos" },
                new Currency { Id = 30, Name = "Ren-Min-Bi yuan", Code3 = "CNY", Symbol = "¥", Plural = "Ren-Min-Bi yuan" },
                new Currency { Id = 31, Name = "Colombian peso", Code3 = "COP", Symbol = "$", Plural = "Colombian pesos" },
                new Currency { Id = 32, Name = "Costa Rican colon", Code3 = "CRC", Symbol = "₡", Plural = "Costa Rican colones" },
                new Currency { Id = 33, Name = "Cuban peso", Code3 = "CUP", Symbol = "₱", Plural = "Cuban pesos" },
                new Currency { Id = 34, Name = "Cape Verde escudo", Code3 = "CVE", Symbol = "Esc", Plural = "Cape Verde escudos" },
                new Currency { Id = 35, Name = "Czech koruna", Code3 = "CZK", Symbol = "Kč", Plural = "Czech korun" },
                new Currency { Id = 36, Name = "Djibouti franc", Code3 = "DJF", Symbol = "₣", Plural = "Djibouti francs" },
                new Currency { Id = 37, Name = "Danish krone", Code3 = "DKK", Symbol = "kr", Plural = "Danish kroner" },
                new Currency { Id = 38, Name = "Dominican peso", Code3 = "DOP", Symbol = "RD$", Plural = "Dominican pesos" },
                new Currency { Id = 39, Name = "Algerian dinar", Code3 = "DZD", Symbol = "د.ج", Plural = "Algerian dinars" },
                new Currency { Id = 40, Name = "Estonian kroon", Code3 = "EEK", Symbol = "kr", Plural = "Estonian krooni" },
                new Currency { Id = 41, Name = "Egyptian pound", Code3 = "EGP", Symbol = "E £", Plural = "Egyptian pounds" },
                new Currency { Id = 42, Name = "Nakfa", Code3 = "ERN", Symbol = "Nfk", Plural = "Nakfas" },
                new Currency { Id = 43, Name = "Ethiopian birr", Code3 = "ETB", Symbol = "Br", Plural = "Ethiopian birrs" },
                new Currency { Id = 44, Name = "Euro", Code3 = "EUR", Symbol = "€", Plural = "Euros" },
                new Currency { Id = 45, Name = "Fiji dollar", Code3 = "FJD", Symbol = "$", Plural = "Fiji dollars" },
                new Currency { Id = 46, Name = "Falkland Islands (Malvinas) pound", Code3 = "FKP", Symbol = "£", Plural = "Falkland Islands (Malvinas) pounds" },
                new Currency { Id = 47, Name = "Pound sterling", Code3 = "GBP", Symbol = "£", Plural = "Pounds sterling" },
                new Currency { Id = 48, Name = "Lari", Code3 = "GEL", Symbol = "ლ", Plural = "Lari" },
                new Currency { Id = 49, Name = "Ghana cedi", Code3 = "GHS", Symbol = "GH¢", Plural = "Ghana cedis" },
                new Currency { Id = 50, Name = "Gibraltar pound", Code3 = "GIP", Symbol = "£", Plural = "Gibraltar pounds" },
                new Currency { Id = 51, Name = "Dalasi", Code3 = "GMD", Symbol = "D", Plural = "Dalasi" },
                new Currency { Id = 52, Name = "Guinean franc", Code3 = "GNF", Symbol = "₣", Plural = "Guinean francs" },
                new Currency { Id = 53, Name = "Quetzal", Code3 = "GTQ", Symbol = "Q", Plural = "Quetzales" },
                new Currency { Id = 54, Name = "Guinea-Bissau peso", Code3 = "GWP", Symbol = "$", Plural = "Guinea-Bissau pesos" },
                new Currency { Id = 55, Name = "Guyana dollar", Code3 = "GYD", Symbol = "$", Plural = "Guyana dollars" },
                new Currency { Id = 56, Name = "Hong Kong dollar", Code3 = "HKD", Symbol = "$", Plural = "Hong Kong dollars" },
                new Currency { Id = 57, Name = "Lempira", Code3 = "HNL", Symbol = "L", Plural = "Lempiras" },
                new Currency { Id = 58, Name = "Kuna", Code3 = "HRK", Symbol = "kn", Plural = "Kunas" },
                new Currency { Id = 59, Name = "Haitian gourde", Code3 = "HTG", Symbol = "G", Plural = "Haitian gourdes" },
                new Currency { Id = 60, Name = "Forint", Code3 = "HUF", Symbol = "Ft", Plural = "Forints" },
                new Currency { Id = 61, Name = "Rupiah", Code3 = "IDR", Symbol = "Rp", Plural = "Rupiahs" },
                new Currency { Id = 62, Name = "New Israeli sheqel", Code3 = "ILS", Symbol = "₪", Plural = "New Israeli sheqels" },
                new Currency { Id = 63, Name = "Indian rupee", Code3 = "INR", Symbol = "₹", Plural = "Indian rupees" },
                new Currency { Id = 64, Name = "Iraqi dinar", Code3 = "IQD", Symbol = "د.ع", Plural = "Iraqi dinars" },
                new Currency { Id = 65, Name = "Iranian rial", Code3 = "IRR", Symbol = "﷼", Plural = "Iranian rials" },
                new Currency { Id = 66, Name = "Icelandic króna", Code3 = "ISK", Symbol = "kr", Plural = "Icelandic krónur" },
                new Currency { Id = 67, Name = "Jamaican dollar", Code3 = "JMD", Symbol = "J$", Plural = "Jamaican dollars" },
                new Currency { Id = 68, Name = "Jordanian dinar", Code3 = "JOD", Symbol = "د.ا", Plural = "Jordanian dinars" },
                new Currency { Id = 69, Name = "Yen", Code3 = "JPY", Symbol = "¥", Plural = "Yen" },
                new Currency { Id = 70, Name = "Kenyan shilling", Code3 = "KES", Symbol = "SH", Plural = "Kenyan shillings" },
                new Currency { Id = 71, Name = "Kyrgyz Som", Code3 = "KGS", Symbol = "лв", Plural = "Kyrgyz Soms" },
                new Currency { Id = 72, Name = "Riel", Code3 = "KHR", Symbol = "៛", Plural = "Riels" },
                new Currency { Id = 73, Name = "Comoro franc", Code3 = "KMF", Symbol = "₣", Plural = "Comoro francs" },
                new Currency { Id = 74, Name = "Won", Code3 = "KRW", Symbol = "₩", Plural = "Won" },
                new Currency { Id = 75, Name = "Kuwaiti dinar", Code3 = "KWD", Symbol = "د.ك", Plural = "Kuwaiti dinars" },
                new Currency { Id = 76, Name = "Cayman Islands dollar", Code3 = "KYD", Symbol = "$", Plural = "Cayman Islands dollars" },
                new Currency { Id = 77, Name = "Tenge", Code3 = "KZT", Symbol = "лв", Plural = "Tenge" },
                new Currency { Id = 78, Name = "Kip", Code3 = "LAK", Symbol = "₭", Plural = "Kips" },
                new Currency { Id = 79, Name = "Lebanese pound", Code3 = "LBP", Symbol = "LBP", Plural = "Lebanese pounds" },
                new Currency { Id = 80, Name = "Sri Lankan rupee", Code3 = "LKR", Symbol = "₨", Plural = "Sri Lankan rupees" },
                new Currency { Id = 81, Name = "Liberian dollar", Code3 = "LRD", Symbol = "$", Plural = "Liberian dollars" },
                new Currency { Id = 82, Name = "Loti", Code3 = "LSL", Symbol = "M", Plural = "Maloti" },
                new Currency { Id = 83, Name = "Lithuanian litus", Code3 = "LTL", Symbol = "Lt", Plural = "Lithuanian litai" },
                new Currency { Id = 84, Name = "Latvian lats", Code3 = "LVL", Symbol = "Ls", Plural = "Latvian lats" },
                new Currency { Id = 85, Name = "Libyan dinar", Code3 = "LYD", Symbol = "ل.د", Plural = "Libyan dinar" },
                new Currency { Id = 86, Name = "Moroccan dirham", Code3 = "MAD", Symbol = "د.م", Plural = "Moroccan dirhams" },
                new Currency { Id = 87, Name = "Moldovan leu", Code3 = "MDL", Symbol = "L", Plural = "Moldovan lei" },
                new Currency { Id = 88, Name = "Malagasy Ariary", Code3 = "MGA", Symbol = "Ar", Plural = "Malagasy Ariaries" },
                new Currency { Id = 89, Name = "Denar", Code3 = "MKD", Symbol = "ден", Plural = "Denari" },
                new Currency { Id = 90, Name = "Kyat", Code3 = "MMK", Symbol = "K", Plural = "Kyats" },
                new Currency { Id = 91, Name = "Tugrik", Code3 = "MNT", Symbol = "₮", Plural = "Tugriks" },
                new Currency { Id = 92, Name = "Pataca", Code3 = "MOP", Symbol = "MOP$", Plural = "Patacas" },
                new Currency { Id = 93, Name = "Ouguiya", Code3 = "MRO", Symbol = "UM", Plural = "Ouguiyas" },
                new Currency { Id = 94, Name = "Ouguiya", Code3 = "MRU", Symbol = "UM", Plural = "Ouguiyas" },
                new Currency { Id = 95, Name = "Mauritian rupee", Code3 = "MUR", Symbol = "₨", Plural = "Mauritian rupees" },
                new Currency { Id = 96, Name = "Rufiyaa", Code3 = "MVR", Symbol = "Rf", Plural = "Rufiyaas" },
                new Currency { Id = 97, Name = "Kwacha", Code3 = "MWK", Symbol = "MK", Plural = "Kwacha" },
                new Currency { Id = 98, Name = "Mexican peso", Code3 = "MXN", Symbol = "$", Plural = "Mexican pesos" },
                new Currency { Id = 99, Name = "Malaysian ringgit", Code3 = "MYR", Symbol = "RM", Plural = "Malaysian ringgit" },
                new Currency { Id = 100, Name = "Metical", Code3 = "MZN", Symbol = "MT", Plural = "Meticais" },
                new Currency { Id = 101, Name = "Namibian dollar", Code3 = "NAD", Symbol = "N$", Plural = "Namibian dollar" },
                new Currency { Id = 102, Name = "Naira", Code3 = "NGN", Symbol = "₦", Plural = "Naira" },
                new Currency { Id = 103, Name = "Cordoba Oro", Code3 = "NIO", Symbol = "C$", Plural = "Cordobas Oro" },
                new Currency { Id = 104, Name = "Norwegian krone", Code3 = "NOK", Symbol = "kr", Plural = "Norwegian kroner" },
                new Currency { Id = 105, Name = "Nepalese rupee", Code3 = "NPR", Symbol = "₨", Plural = "Nepalese rupees" },
                new Currency { Id = 106, Name = "New Zealand dollar", Code3 = "NZD", Symbol = "$", Plural = "New Zealand dollars" },
                new Currency { Id = 107, Name = "Omani rial", Code3 = "OMR", Symbol = "﷼", Plural = "Omani rials" },
                new Currency { Id = 108, Name = "Balboa", Code3 = "PAB", Symbol = "B/.", Plural = "Balboas" },
                new Currency { Id = 109, Name = "Nuevo Sol", Code3 = "PEN", Symbol = "S/.", Plural = "Nuevo Soles" },
                new Currency { Id = 110, Name = "Kina", Code3 = "PGK", Symbol = "K", Plural = "Kinas" },
                new Currency { Id = 111, Name = "Philippine peso", Code3 = "PHP", Symbol = "Php", Plural = "Philippine pesos" },
                new Currency { Id = 112, Name = "Pakistani rupee", Code3 = "PKR", Symbol = "₨", Plural = "Pakistani rupees" },
                new Currency { Id = 113, Name = "Zloty", Code3 = "PLN", Symbol = "zł", Plural = "Zloty" },
                new Currency { Id = 114, Name = "Guarani", Code3 = "PYG", Symbol = "Gs", Plural = "Guaranis" },
                new Currency { Id = 115, Name = "Qatari riyal", Code3 = "QAR", Symbol = "﷼", Plural = "Qatari riyals" },
                new Currency { Id = 116, Name = "New Leu", Code3 = "RON", Symbol = "lei", Plural = "New Lei" },
                new Currency { Id = 117, Name = "Serbian dinar", Code3 = "RSD", Symbol = "Дин.", Plural = "Serbian dinars" },
                new Currency { Id = 118, Name = "Russian rouble", Code3 = "RUB", Symbol = "руб", Plural = "Russian roubles" },
                new Currency { Id = 119, Name = "Rwanda franc", Code3 = "RWF", Symbol = "R₣", Plural = "Rwanda francs" },
                new Currency { Id = 120, Name = "Saudi riyal", Code3 = "SAR", Symbol = "﷼", Plural = "Saudi riyals" },
                new Currency { Id = 121, Name = "Solomon Islands dollar", Code3 = "SBD", Symbol = "SI$", Plural = "Solomon Islands dollars" },
                new Currency { Id = 122, Name = "Seychelles rupee", Code3 = "SCR", Symbol = "₨", Plural = "Seychelles rupees" },
                new Currency { Id = 123, Name = "Sudanese pound", Code3 = "SDG", Symbol = "£", Plural = "Sudanese pounds" },
                new Currency { Id = 124, Name = "Swedish krona", Code3 = "SEK", Symbol = "kr", Plural = "Swedish kronur" },
                new Currency { Id = 125, Name = "Singapore dollar", Code3 = "SGD", Symbol = "$", Plural = "Singapore dollars" },
                new Currency { Id = 126, Name = "Saint Helena pound", Code3 = "SHP", Symbol = "£", Plural = "Saint Helena pounds" },
                new Currency { Id = 127, Name = "Leone", Code3 = "SLL", Symbol = "Le", Plural = "Leones" },
                new Currency { Id = 128, Name = "Somali shilling", Code3 = "SOS", Symbol = "S", Plural = "Somali shillings" },
                new Currency { Id = 129, Name = "Surinam dollar", Code3 = "SRD", Symbol = "$", Plural = "Surinam dollars" },
                new Currency { Id = 130, Name = "South Sudanese pound", Code3 = "SSP", Symbol = "£", Plural = "South Sudanese pounds" },
                new Currency { Id = 131, Name = "Dobra", Code3 = "STD", Symbol = "Db", Plural = "Dobras" },
                new Currency { Id = 132, Name = "El Salvador colon", Code3 = "SVC", Symbol = "$", Plural = "El Salvador colones" },
                new Currency { Id = 133, Name = "Syrian pound", Code3 = "SYP", Symbol = "£S", Plural = "Syrian pounds" },
                new Currency { Id = 134, Name = "Lilangeni", Code3 = "SZL", Symbol = "E", Plural = "Emalangeni" },
                new Currency { Id = 135, Name = "Baht", Code3 = "THB", Symbol = "฿", Plural = "Baht" },
                new Currency { Id = 136, Name = "Somoni", Code3 = "TJS", Symbol = "SM", Plural = "Somonis" },
                new Currency { Id = 137, Name = "Manat", Code3 = "TMM", Symbol = "m", Plural = "Manat" },
                new Currency { Id = 138, Name = "Tunisian dinar", Code3 = "TND", Symbol = "TND", Plural = "Tunisian dinars" },
                new Currency { Id = 139, Name = "Pa'anga", Code3 = "TOP", Symbol = "$", Plural = "Pa'anga" },
                new Currency { Id = 140, Name = "Turkish lira", Code3 = "TRY", Symbol = "TL", Plural = "Turkish liras" },
                new Currency { Id = 141, Name = "Trinidad and Tobago dollar", Code3 = "TTD", Symbol = "TT$", Plural = "Trinidad and Tobago dollars" },
                new Currency { Id = 142, Name = "New Taiwan dollar", Code3 = "TWD", Symbol = "NT$", Plural = "New Taiwan dollars" },
                new Currency { Id = 143, Name = "Tanzanian shilling", Code3 = "TZS", Symbol = "Sh", Plural = "Tanzanian shillings" },
                new Currency { Id = 144, Name = "Hryvnia", Code3 = "UAH", Symbol = "₴", Plural = "Hryvni" },
                new Currency { Id = 145, Name = "Ugandan shilling", Code3 = "UGX", Symbol = "UGX", Plural = "Ugandan shillings" },
                new Currency { Id = 146, Name = "U.S. dollar", Code3 = "USD", Symbol = "$", Plural = "U.S. dollars" },
                new Currency { Id = 147, Name = "Uruguayo peso", Code3 = "UYU", Symbol = "$U", Plural = "Uruguayo pesos" },
                new Currency { Id = 148, Name = "Uzbekistan sum", Code3 = "UZS", Symbol = "лв", Plural = "Uzbekistan sum" },
                new Currency { Id = 149, Name = "Bolivar Fuerte", Code3 = "VEF", Symbol = "Bs", Plural = "Bolivares Fuerte" },
                new Currency { Id = 150, Name = "Dong", Code3 = "VND", Symbol = "₫", Plural = "Dongs" },
                new Currency { Id = 151, Name = "Vatu", Code3 = "VUV", Symbol = "VT", Plural = "Vatu" },
                new Currency { Id = 152, Name = "Samoan Tala", Code3 = "WST", Symbol = "$", Plural = "Samoan Talas" },
                new Currency { Id = 153, Name = "CFA Franc - BEAC", Code3 = "XAF", Symbol = "Fr", Plural = "CFA Francs - BEAC" },
                new Currency { Id = 154, Name = "Eastern Caribbean dollar", Code3 = "XCD", Symbol = "$", Plural = "Eastern Caribbean dollars" },
                new Currency { Id = 155, Name = "CFA franc - BCEAO", Code3 = "XOF", Symbol = "CFA", Plural = "CFA francs - BCEAO" },
                new Currency { Id = 156, Name = "Comptoirs Francais du Pacifique Francs", Code3 = "XPF", Symbol = "₣", Plural = "Comptoirs Francais du Pacifique Francs" },
                new Currency { Id = 157, Name = "Yemeni rial", Code3 = "YER", Symbol = "﷼", Plural = "Yemeni rials" },
                new Currency { Id = 158, Name = "Rand", Code3 = "ZAR", Symbol = "R", Plural = "Rand" },
                new Currency { Id = 159, Name = "Kwacha", Code3 = "ZMK", Symbol = "ZK", Plural = "Kwachas" },
                new Currency { Id = 160, Name = "Kwacha", Code3 = "ZMW", Symbol = "ZK", Plural = "Kwachas" },
                new Currency { Id = 161, Name = "Zimbabwean dollar", Code3 = "ZWD", Symbol = "Z$", Plural = "Zimbabwean dollars" }
            };
        }
    }
}
